In [65]:
import numpy as np


Q=[[5,3,0,1],[4,0,0,1],[1,1,0,5],[1,0,0,4],[0,1,5,4]]
Q = np.array(Q)
print(Q)

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]


In [66]:
W = Q>0
W

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True]])

In [67]:
W = W * 1
W

array([[1, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 1]])

In [68]:
lambda_ = 0.001
n_factors = 3
m, n = Q.shape
n_iterations = 20

In [69]:
X = 5 * np.random.rand(m, n_factors) 
Y = 5 * np.random.rand(n_factors, n)

In [70]:
X

array([[0.9354398 , 2.67111171, 0.3327935 ],
       [3.06622681, 1.5979841 , 3.87532324],
       [4.84919766, 4.42377823, 0.4845187 ],
       [1.7268013 , 4.49343039, 1.21400538],
       [2.32156956, 2.10985944, 2.72221263]])

In [71]:
Y

array([[2.46882868, 0.43899893, 0.69388116, 2.182868  ],
       [2.39441754, 0.62826686, 4.88920407, 2.03933859],
       [0.54020096, 4.83716031, 1.02610716, 0.48316345]])

In [72]:
import time

In [73]:
W

array([[1, 1, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 1]])

In [74]:
for u,Wu in enumerate(W):
    print(u)
    print(Wu)

0
[1 1 0 1]
1
[1 0 0 1]
2
[1 1 0 1]
3
[1 0 0 1]
4
[0 1 1 1]


In [75]:
weighted_errors =[]

start = time.time()

for ii in range(n_iterations):
    
    for u, Wu in enumerate(W):
        
        X[u] = np.linalg.solve(np.dot(Y, np.dot(np.diag(Wu), Y.T)) + lambda_ * (np.linalg.norm(Y)**2), np.dot(Y, np.dot(np.diag(Wu), Q[u].T))).T
        
    for i, Wi in enumerate(W.T):
            
        Y[:,i] = np.linalg.solve(np.dot(X.T, np.dot(np.diag(Wi), X))+ lambda_ * (np.linalg.norm(X)**2), np.dot(X.T, np.dot(np.diag(Wi), Q[:, i])))

    error = np.sum((W * (Q - np.dot(X, Y)))**2)
    print(error)
    weighted_errors.append(error)
    
    elapsed = (start-time.time())

    Q_hat = np.dot(X,Y)

37.34878354344798
6.4481897436342885
1.752245925040639
0.04714231957293116
0.027436330604959987
0.02162089783549907
0.016931587311581994
0.01345868450129202
0.010810549023475098
0.008538997012511644
0.007136874338570847
0.0009731100020001957
0.0006910370194470599
0.0005381814946738072
0.00041598753267976167
0.0003215791896375162
0.0002487084386353092
0.00018796607058009306
0.00014737992381844533
0.0001135407189786447


In [76]:
np.linalg.solve(
    np.dot(Y, np.dot(np.diag(Wu), Y.T)) + lambda_ * np.linalg.norm(Y)**2, 
    np.dot(Y, np.dot(np.diag(Wu), Q[u].T))
).T

array([ 26.62991086, -27.05308484,   0.42317398])